"""add packs, tags, events, event_tags tables

Revision ID: 35e486d9bbf2
Revises: 4a5803156a3d
Create Date: 2026-10-09 20:42:22.296236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = '35e486d9bbf2'
down_revision: Union[str, Sequence[str], None] = '4a5803156a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags_count', sa.Integer(), nullable=False),
    sa.Column('master_auth_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packs_master_auth_hash'), 'packs', ['master_auth_hash'], unique=True)
    op.create_index(op.f('ix_packs_owner_id'), 'packs', ['owner_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_pack_id'), 'events', ['pack_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pack_id', sa.Uuid(), nullable=False),
    sa.Column('static_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_pack_id'), 'tags', ['pack_id'], unique=False)
    op.create_index(op.f('ix_tags_static_hash'), 'tags', ['static_hash'], unique=True)
    op.create_table('event_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('tag_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_tags_event_id'), 'event_tags', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_tags_tag_id'), 'event_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_tags_tag_id'), table_name='event_tags')
    op.drop_index(op.f('ix_event_tags_event_id'), table_name='event_tags')
    op.drop_table('event_tags')
    op.drop_index(op.f('ix_tags_static_hash'), table_name='tags')
    op.drop_index(op.f('ix_tags_pack_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_events_pack_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_packs_owner_id'), table_name='packs')
    op.drop_index(op.f('ix_packs_master_auth_hash'), table_name='packs')
    op.drop_table('packs')
    # ### end Alembic commands ###
