"""add sequence and is_printed to tags

Revision ID: 39a4862d0f90
Revises: 94fa227bd302
Create Date: 2026-10-10 11:13:53.442095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39a4862d0f90'
down_revision: Union[str, Sequence[str], None] = '94fa227bd302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('sequence_num', sa.Integer(), server_default='1', nullable=False))
    op.add_column('tags', sa.Column('is_printed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'is_printed')
    op.drop_column('tags', 'sequence_num')
    # ### end Alembic commands ###
